// services/groq.ts
export async function generateMetadata(prompt: string): Promise<{ title: string; description: string; tags: string[] }> {
  const system = `You are a professional social media content creator. Generate a catchy title, a compelling description, and 5 relevant tags for a video based on the user's prompt. Output ONLY valid JSON with keys: "title", "description", "tags".`;
  
  const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${Deno.env.get("GROQ_API_KEY")}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "llama3-8b-8192",
      messages: [
        { role: "system", content: system },
        { role: "user", content: prompt },
      ],
      temperature: 0.7,
      max_tokens: 300,
    }),
  });

  if (!res.ok) throw new Error(`Groq API error: ${res.statusText}`);
  const json = await res.json();
  let content = json.choices[0]?.message?.content?.trim() || "{}";
  
  // Tozalash: ba'zan ```json bilan keladi
  if (content.startsWith("```")) {
    content = content.slice(content.indexOf("{"));
    content = content.slice(0, content.lastIndexOf("}") + 1);
  }

  try {
    const parsed = JSON.parse(content);
    return {
      title: parsed.title || "Untitled Video",
      description: parsed.description || "Generated by AI",
      tags: Array.isArray(parsed.tags) ? parsed.tags : [],
    };
  } catch (e) {
    console.error("Groq response parse error:", content);
    return {
      title: "Auto-Generated Video",
      description: prompt,
      tags: ["ai", "automation"],
    };
  }
}
